#! /usr/bin/env bash

# shellcheck disable=SC1091
. bpm
bpm::include assign
bpm::include strict
. lib/bash-tokenizer

bash-minifier::help() {
    cat <<'EOF'
Bash Minifier

Parses a shell script and writes a minified version to stdout.

Usage:

    bash-minifier INPUT_FILE > OUTPUT_FILE
EOF
}

bash-minifier::load() {
    local content=()

    while IFS=$'\n' read -r line; do
        content[${#content[@]}]=$line
    done < <(cat -- "$2")

    local "$1" && assign::array "$1" "${content[@]}"
}

bash-minifier::token() {
    local "$1" && assign::value "$1" "$2@$3:$4 $5"
}

bash-minifier() {
    local content filename

    strict::mode
    filename=${1-}

    if [[ ! -f "$filename" ]] && [[ "$filename" != "-" ]]; then
        filename=
    fi

    if [[ -z "$filename" ]]; then
        bash-minifier::help

        exit 1
    fi

    content=$(cat -- "$filename"; echo x)
    content=${content%x}
    bash-tokenizer::tokenize "$content"
}

if ! bpm::isSourced; then
    bash-minifier ${@+"$@"}
fi
